# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install serverless -g'
- task: CmdLine@2
  inputs:
    script: 'npm install serverless -g'
- task: Npm@1
  inputs:
    command: 'install'